# Site settings
title: Alexey Shiklomanov
email: ashiklom@bu.edu
description: Ph.D Geography student, BU Department of Earth & Environment
baseurl: ""
url: "http://ashiklom.github.io"

author:
  name     : 'Alexey Shiklomanov'
  email    : ashiklom@bu.edu
  url      : ashiklom.github.io
  facebook : http://www.facebook.com/redrussianrage
  #twitter  : 

github: https://github.com/ashiklom
#disqus_shortname: 
#google_analytics: 

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
