# Site settings
title: Alexey Shiklomanov
email: ashiklom@bu.edu
description: Ph.D Geography student, BU Department of Earth & Environment
baseurl: ""
url: "http://ashiklom.github.io"

author:
    name     : 'Alexey Shiklomanov'
    email    : ashiklom@bu.edu
    url      : ashiklom.github.io
    #facebook : 
    #twitter  : 
    linkedin : http://www.linkedin.com/in/ashiklom
    researchgate : http://www.researchgate.com/profile/Alexey_Shiklomanov
    github : http://github.com/ashiklom

github: https://github.com/ashiklom/ashiklom.github.io
disqus_shortname: ashiklomgithubio
google_analytics: UA-70848532-1

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
    style: :compressed
    sass_dir: _sass

# Build settings
markdown  : kramdown
#markdown : redcarpet
extensions: [fenced_code_blocks]
# NOTE: kramdown uses different fenced code block syntax: ~~~ instead of ```

gems:
    - jekyll-gist

permalink : /:title/
